spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=branch_334
    username: try_334
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8889
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    config:
      Dao:
        DEBUG